#pragma once

#include "Tool.h"
#include "voxel\VoxelTool.h"
#include "voxel\VTAdd.h"
#include "voxel\VTErase.h"
#include "voxel\VTReplace.h"
#include "voxel\fill\VFTAdd.h"
#include "voxel\fill\VFTErase.h"
#include "voxel\fill\VFTReplace.h"
#include "voxel\single\VSTEyedrop.h"
#include "matrix\MatrixTool.h"
#include "matrix\MTMove.h"
#include "matrix\MTResize.h"
#include "matrix\MTSelect.h"
